### ISSUE TITLE
code

### ISSUE THREAD

**Issue by stefanocudini** [smathermather/pg-orthogonalize#1]
when will you publish a bit of code? :)

**Comment by smathermather** [comment]
Hi @stefanocudini -- this dropped to a very low priority... I am sorry. I don't know when I'll get to it.

**Comment by stefanocudini** [comment]
vabbe allora purio sobbono aapri erepo a buffo

mmmmh ok bye

@simonefenix @guidofenix

**Comment by smathermather** [comment]
Agreed, @stefanocudini -- if I opened a repo, I should have added code. Sorry to disappoint. If you are reading the PostGIS Cookbook, I hope that otherwise it does not disappoint. Cheers.
